#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an RPM
#

# Pull base image
FROM suse/sles:12.3
MAINTAINER daos-stack <daos@daos.groups.io>

# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Add build user (to keep rpmbuild happy)
ENV USER build
RUN useradd -u $UID -ms /bin/bash $USER
RUN groupadd -g $UID $USER

# Install basic tools
RUN zypper --non-interactive update

# Hack until the sles image is rebuilt
run zypper nr http-10.8.0.10-418afa6f A_sdkupdate-sles12.3-x86_64; \
    zypper mr --name A_sdkupdate-sles12.3-x86_64 http-10.8.0.10-418afa6f; \
    zypper nr http-10.8.0.10-a977da21 B_updates-sles12.3-x86_64; \
    zypper mr --name B_updates-sles12.3-x86_64 http-10.8.0.10-a977da21; \
    zypper rr http-10.8.0.10-2a04a526; \
    zypper rr http-10.8.0.10-33b60288; \
    zypper rr http-10.8.0.10-4e00da6f; \
    zypper rr http-10.8.0.10-82d67f5b; \
    zypper --non-interactive --gpg-auto-import-keys --no-gpg-checks refresh

# basic building
ENV OPENSUSE_REPO="https://download.opensuse.org/repositories"
ENV TOOLS_12_3A="openSUSE:/Tools/SLE_12_SP3/openSUSE:Tools.repo"
ENV TOOLS_12_3="${OPENSUSE_REPO}/${TOOLS_12_3A}"

RUN zypper --non-interactive ar ${TOOLS_12_3}; \
    zypper --non-interactive --gpg-auto-import-keys refresh
RUN zypper --non-interactive install autoconf automake build                  \
                                     ca-certificates-mozilla curl createrepo  \
                                     git libtool lsb-release make             \
                                     perl-libwww-perl perl-LWP-Protocol-https \
                                     perl-XML-Parser rpm-build sudo

# need to run the build command as root, as it needs to chroot
RUN echo "#includedir /etc/sudoers.d" >> /etc/sudoers; \
    echo "build ALL=(ALL) NOPASSWD: /usr/bin/build" > /etc/sudoers.d/build

ARG JENKINS_URL=""
ENV JENKINS_PATH="${JENKINS_URL}job/daos-stack/job"
ENV JENKINS_ART="lastSuccessfulBuild/artifact/artifacts"
ARG MNGE_BRANCH="master"
RUN zypper --non-interactive ar --gpgcheck-allow-unsigned -f \
    ${JENKINS_PATH}/munge/job/${MNGE_BRANCH}/${JENKINS_ART}/sles12.3/ munge; \
    zypper --non-interactive ref munge

# Suse build utility needs this refresh.
# And the zypper lr report is handy to have.
ARG CACHEBUST=1
RUN zypper --non-interactive --no-gpg-checks refresh; zypper lr --details

